spring:
  application:
    name: lookGo-backend
  profiles:
    active: dev
  datasource:
    url: jdbc:sqlserver://${DB_HOST:localhost}:${DB_PORT:1433};databaseName=${DB_NAME};encrypt=true;trustServerCertificate=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  sql:
    init:
      mode: always
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}

management:
  endpoint:
    health:
      show-details: always

mybatis:
  mapper-locations: classpath:mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true

app:
  admin:
    email: ${ADMIN_EMAIL:admin@example.com}
    username: ${ADMIN_USERNAME:admin}
    password: ${ADMIN_PASSWORD}
  # sendgrid:
  #   api:
  #     key: ${SENDGRID_API_KEY}
  #   from:
  #     email: test@domain.com
  #     name: LookGo
  #   sandbox:
  #     mode: true

frontend:
  base-url: ${FRONTEND_BASE_URL:http://localhost:8081}

logging:
  level:
    com.mli.lookgo.module.auth.security: DEBUG
    com.mli.lookgo.module.user.controller: DEBUG
